---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    channel: eslint-3
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- config/
- dist/
- node_modules/
- tests/
- vendor/
